In [1]:
from sklearn import datasets

In [96]:
iris = datasets.load_iris()

In [5]:
type(iris.data)

numpy.ndarray

In [6]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [19]:
import pandas as pd
import numpy as np

In [12]:
type(iris)

sklearn.datasets.base.Bunch

In [20]:
#df3 = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])

In [143]:
iris_df = pd.DataFrame(iris.data)

In [144]:
iris_df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [145]:
iris_df.columns[0]


0

In [146]:
iris.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [147]:
iris_df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [148]:
iris_df.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [149]:
backUp = iris_df.copy()

In [150]:
def getNewValue(column):
    if column >= 4.3 and column < 5.2:
        return 0
    elif column >= 5.2 and column < 6.1:
        return 1
    elif column >= 6.1 and column < 7.0:
        return 2
    else:
        return 3
    
iris_df['new_col0'] = iris_df[0].apply(getNewValue)

In [151]:
def getNewValue1(column) :
    if column >= 2.0 and column < 2.6:
        return 0;
    elif column >= 2.6 and column < 3.2:
        return 1
    elif column >= 3.2 and column < 3.8 :
        return 2
    else :
        return 3
    
iris_df['new_col1'] = iris_df[1].apply(getNewValue1)

In [152]:

def getNewValue2(column):
    if column >= 1.0 and column < 2.475:
        return 0
    elif column >= 2.475 and column < 3.95:
        return 1
    elif column >= 3.95 and column < 5.425:
        return 2
    else:
        return 3
    
iris_df['new_col2'] = iris_df[2].apply(getNewValue2)

In [153]:
def getNewValue3(column) : 
    if column >= 0.1 and column < 0.7:
        return 0
    elif column >= 0.7 and column < 1.3:
        return 1
    elif column >= 1.3 and column < 1.9:
        return 2
    else:
        return 3
    
iris_df['new_col3'] = iris_df[3].apply(getNewValue3)

In [154]:
iris_df.head()

0    1    2    3  new_col0  new_col1  new_col2  new_col3
0  5.1  3.5  1.4  0.2         0         2         0         0
1  4.9  3.0  1.4  0.2         0         1         0         0
2  4.7  3.2  1.3  0.2         0         2         0         0
3  4.6  3.1  1.5  0.2         0         1         0         0
4  5.0  3.6  1.4  0.2         0         2         0         0

In [155]:
del iris_df[0]
del iris_df[1]
del iris_df[2]
del iris_df[3]

In [156]:
iris_df.head()

new_col0  new_col1  new_col2  new_col3
0         0         2         0         0
1         0         1         0         0
2         0         2         0         0
3         0         1         0         0
4         0         2         0         0

In [158]:
from sklearn import naive_bayes as nb

In [161]:
clf = nb.MultinomialNB()
clf.fit(iris_df, iris.target)
y_pred = clf.predict(iris_df)

In [162]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1,
       1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1])

In [164]:
clf.score(iris_df, iris.target)

0.69999999999999996